#include <stdio.h>
#include <stdlib.h>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "lab09.pio.h"

#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define WS2812_PIN 28       // The GPIO pin that the WS2812 connected to
int rawADC = 0; // to store the raw voltage from ARM

// Must declare the main assembly entry point before use.
void main_asm();

/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}

/**
 * @brief Function to generate an unsigned 32-bit composit GRB
 *        value by combining the individual 8-bit paramaters for
 *        red, green and blue together in the right order.
 * 
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composit 32-bit RGB value
 */
static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  | ((uint32_t) (g) << 16) | (uint32_t) (b);
}

/**
 * @brief Wrapper function to set the LED to dispay RED colour
 * 
 */
void set_red_on(){
    put_pixel(urgb_u32(0x7F, 0x00, 0x00));
}

/**
 * @brief Wrapper function to set the LED to dispay GREEN colour
 * 
 */
void set_green_on(){
    put_pixel(urgb_u32(0x00, 0x7F, 0x00));
}

/**
 * @brief Wrapper function to set the LED to dispay ORANGE colour
 * 
 */
void set_orange_on(){
    put_pixel(urgb_u32(0xFF, 0x55, 0x00));
}

/**
 * @brief Takes the current temperature as input to sort out the correct LED based on it
 * 
 * @param temp_in_C holds the current temperature in centigrate
 */
void set_correct_led(int temp_in_C){
    if (temp_in_C <=  10)set_green_on();
    else if (temp_in_C <= 25)set_orange_on();
    else set_red_on();
}
/**
 * @brief function to calculate the temperature from the given raw ADC voltage from ARM in Celsius
 * 
 */
void calc_temperature(){
    float temp = 437 - (rawADC / 2.15);
    printf("%d - %.2f Celsius\n", rawADC, temp);
    set_correct_led(temp);
}
/**
 * @brief LAB #09 - TEMPLATE
 *        Main entry point for the code - calls the main assembly
 *        function where the body of the code is implemented.
 * 
 * @return int      Returns exit-status zero on completion.
 */
int main() {

    stdio_init_all(); //initialise uart outpout
    //initialise the RGB LED on the Pi PICO
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, IS_RGBW);
    // Jump into the main assembly code subroutine.
    main_asm(&rawADC); //pass the address of the global variable to ARM

    // Returning zero indicates everything went okay.
    return 0;
}
